PROJECT_NAME = ENV["PROJECT_NAME"]
XCODE_WORKSPACE = ENV["XCODE_WORKSPACE"]
APP_IDENTIFIER = ENV["APP_IDENTIFIER"]
PROVISIONING_PROFILE = ENV["PROVISIONING_PROFILE"]
CONNECT_APP_ID = ENV["CONNECT_APP_ID"]
GIT_AUTHORIZATION = ENV["GIT_AUTHORIZATION"]

lane :release do

    api_key = app_store_connect_api_key(
        key_id: "28FWF9S5YL",
        issuer_id: "2d0826cc-c60d-4d95-8dcb-9415470672d5",
        key_content: "-----BEGIN PRIVATE KEY-----
        MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg83LfvR3qs+U9lpQC
        rMgmRamP1nhS8/IBtAmERdRDZxqgCgYIKoZIzj0DAQehRANCAAROdQn3qpPr5PPH
        cRZ1x7sPiswUxj12pC/2GNiiD1ZcG2orbSlYrezWobZRo3pYAWwvLJypSCQn/m30
        H/dAg5CG
        -----END PRIVATE KEY-----"
    )

    increment_build_number({
        build_number: latest_testflight_build_number + 1,
        api_key: key_id
    })

    create_keychain(
        name: "name",
        password: "password",
        unlock: true,
        timeout: 3600
    )

    match(
        type: 'appstore',
        git_basic_authorization: Base64.strict_encode64(GIT_AUTHORIZATION),
        readonly: true,
        keychain_name: "name",
        keychain_password: "password" 
    )

    gym(
        scheme: PROJECT_NAME,
        workspace: XCODE_WORKSPACE,
        silent: true,
        configuration: "Release",
        export_method: "app-store",
        export_options: {
            provisioningProfiles: { 
                APP_IDENTIFIER => PROVISIONING_PROFILE
            }
        }
    )

    pilot(
        apple_id: CONNECT_APP_ID,
        skip_waiting_for_build_processing: true,
        skip_submission: true,
        distribute_external: false,
        notify_external_testers: false,
        ipa: "./#{PROJECT_NAME}.ipa",
    )

end