export const CLEAR_REDUCER = 'CLEAR_REDUCER';
export const LOGIN = 'LOGIN';
export const CHANGE_THEME = 'CHANGE_THEME';
export const CHANGE_FONT = 'CHANGE_FONT';
export const FORCE_APPEARANCE = 'FORCE_APPEARANCE';
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
export const SAVE_ONBOARD = 'SAVE_ONBOARD';
