export const Images = {
  logo: require('@assets/images/logo.png'),
  icon: require('@assets/images/icon.png'),
  onboard1: require('@assets/images/onboard1.png'),
  onboard2: require('@assets/images/onboard2.png'),
  onboard3: require('@assets/images/onboard3.png'),
  signin: require('@assets/images/signin.png'),
  empty: require('@assets/images/empty.png'),
  banner: require('@assets/images/banner.jpg'),
  en: require('@assets/images/en.png'),
  vi: require('@assets/images/vi.png'),
  ar: require('@assets/images/ar.png'),
  da: require('@assets/images/da.png'),
  de: require('@assets/images/de.png'),
  el: require('@assets/images/el.png'),
  fr: require('@assets/images/fr.png'),
  he: require('@assets/images/he.png'),
  id: require('@assets/images/id.png'),
  ja: require('@assets/images/ja.png'),
  ko: require('@assets/images/ko.png'),
  lo: require('@assets/images/lo.png'),
  nl: require('@assets/images/nl.png'),
  zh: require('@assets/images/zh.png'),
  fa: require('@assets/images/fa.png'),
  km: require('@assets/images/km.png'),
};
