name: Release

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: macos-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install node_modules
        run: npm install

      - name: Install Pods
        run: cd ios && pod install 

      - name: iOS Build & Upload
        env:
          MATCH_PASSWORD: "${{ secrets.MATCH_PASSWORD }}"
          DEVELOPER_APPLE_ID: "${{ secrets.DEVELOPER_APPLE_ID }}"
          PROJECT_NAME: "${{ secrets.PROJECT_NAME }}"
          XCODE_WORKSPACE: "${{ secrets.XCODE_WORKSPACE }}"
          APP_IDENTIFIER: "${{ secrets.APP_IDENTIFIER }}"
          PROVISIONING_PROFILE: "${{ secrets.PROVISIONING_PROFILE }}"
          CONNECT_APP_ID: "${{ secrets.CONNECT_APP_ID }}"
          GIT_AUTHORIZATION: "${{ secrets.GIT_AUTHORIZATION }}"
          CONNECT_KEY_ID: "${{ secrets.CONNECT_KEY_ID }}"
          CONNECT_ISSUER_ID: "${{ secrets.CONNECT_ISSUER_ID }}"
          CONNECT_KEY_CONTENT: "${{ secrets.CONNECT_KEY_CONTENT }}"
        
        run: cd ios/fastlane && fastlane release
        


